name: Check Code Style - Ruff

on:
  push:
    branches: [main, humble, feature/*]
  pull_request:
    branches: [main, humble, feature/*]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
      - uses: astral-sh/ruff-action@v3
      - name: Ruff Check
        run: ruff check --fix
      - name: Ruff Format
        run: ruff format
